### ISSUE TITLE
Using intrinsic Cloud Formation functions (!GetAtt and !ImportValue) when defining the event bus name

### ISSUE THREAD

**Issue by cjuega** [rubenkaiser/serverless-offline-eventBridge#24]
Serverless now supports (from v2.28.0 onwards) to create EventBridge resources using CloudFormation directly instead of using a custom lambda (https://github.com/serverless/serverless/pull/8437).

That enables customers to use CloudFormation intrinsic functions when defining the trigger of a lambda function. For instance:

```YAML
functions:

  consumeEvent:
    handler: events.consume
    events:
      - eventBridge:
          eventBus: !GetAtt EventBus.Arn # Assuming EventBus is a resource already defined in the CF template
```

or

```YAML
  consumeEvent:
    handler: events.consume
    events:
      - eventBridge:
          eventBus: !ImportValue EventBusNameFromOtherStack # Assuming the EventBus is created by a different CF stack
```

The issue comes when we try to run serverless-offline-eventBridge, The above definitions are not supported.

I have extended this plugin to support both scenarios. Are PRs welcomed?
