### ISSUE TITLE
Missing support for schedules

### ISSUE THREAD

**Issue by domdomegg** [rubenkaiser/serverless-offline-eventBridge#41]
It seems that in https://github.com/rubenkaiser/serverless-offline-eventBridge/commit/7f91a14907e434c8d5ef4e301cb98428f2c1fc06 support for scheduled events (e.g. `cron` and `rate` expressions) was removed.

I'm not sure this was intentional - the README still claims "Scheduled events are also supported. When a cron fires the event object that is sent along is an empty object." and scheduled events are a key part of EventBridge.

Could schedule support be reintroduced, or at the very least can the README be corrected to say that scheduled events are not supported. Thanks! :raised_hands:

**Comment by domdomegg** [comment]
Serverless-offline has built-in support for CloudWatch scheduled events, but not EventBridge ones.

Serverless docs on Amazon CloudWatch scheduled events: https://www.serverless.com/framework/docs/providers/aws/events/schedule

Serverless docs on EventBridge scheduled events: https://www.serverless.com/framework/docs/providers/aws/events/event-bridge#setting-up-a-scheduled-event

Serverless-offline implementation: https://github.com/dherault/serverless-offline/blob/2e864d9e627280acba534127c8d905e56d4d9918/src/events/schedule/Schedule.js

Example serverless.yml with Amazon CloudWatch (this probably works with serverless-offline):

```yaml
functions:
  myFunction:
    handler: myFunction
    events:
      - schedule: rate(1 minute)
```

Example serverless.yml with EventBridge (this does not work with serverless-offline, with or without serverless-offline-aws-eventbridge). This is the issue I am reporting:

```yaml
functions:
  myFunction:
    handler: index.handler
    events:
      - eventBridge:
          schedule: rate(1 minute)
```
