### ISSUE TITLE
eventBridge enabled flag is ignored

### ISSUE THREAD

**Issue by rdevraj950** [rubenkaiser/serverless-offline-eventBridge#74]
I've been trying on a personal project to disable an eventBridge with the `enabled` flag for testing purposes. And it doesn't seem to work with offline. See below for an example, am I missing something?

```
consumeEvent:
    handler: events.consume
    events:
      - eventBridge:
          eventBus: marketing
          enabled: false
          pattern:
            source:
              - acme.newsletter.campaign
```
