### ISSUE TITLE
equals-ignore-case filter not found

### ISSUE THREAD

**Issue by rion18** [rubenkaiser/serverless-offline-eventBridge#83]
If I have an eventBridge event that triggers a lambda that uses the equals-ignore-case filter, such as:

```yaml
- eventBridge:
    pattern:
      source:
        - my-awesome-source
      detail:
        info:
          - equals-ignore-case: AwEsOmE-DatA
```

We get hit with the following message:

> The equals-ignore-case eventBridge filter is not supported in serverless-offline-aws-eventBridge yet. Please consider submitting a PR to support it.

Adding a PR very soon.
