### ISSUE TITLE
Query: Does this package have support for the event bridge scheduler

### ISSUE THREAD

**Issue by Rayyan98** [rubenkaiser/serverless-offline-eventBridge#85]
As title

**Comment by rubenkaiser** [comment]
As stated in the docs:

```
functions:
  scheduledEvent:
    handler: events.scheduled
    events:
      - eventBridge:
          eventBus: marketing
          # run every 5 minutes
          schedule: "cron(0/5 * * * ? *)"
```

In this case a cron expression is used, but the other ways to schedule events are also supported.
