### ISSUE TITLE
Support step functions via `serverless-step-functions`

### ISSUE THREAD

**Issue by frangeris** [rubenkaiser/serverless-offline-eventBridge#97]
Hi there,

First, thanks for maintaining this package! 🙌

I have an scenario where I would like to trigger some state machines (already running locally) with the eventbridge definition, this what I have:

_serverless.yml_
```yml
stepFunctions:
  stateMachines:
    test: ${file(./src/my-step-machine.yml)}
```

_my-step-machine.yml_
```yml
// serverless.yml
name: "${self:custom.prefix}-xxx"
events:
  - eventBridge:
      eventBus: !GetAtt EventBridge.Name
      event:
        source:
          - "xxx"
        detail-type:
          - "xx-xxx"
```

I'm able to trigger and run the state machine locally via the integration with serverless offline, but how run it via the bus events?

Plz, correct me If i'm wrong but:

1. Is scheduled events the only supported?

2. In case of adding this integration we will need to change where the plugin gets the "functions" to also include the `stepFunctions` key?

I mean this call:
https://github.com/rubenkaiser/serverless-offline-eventBridge/blob/master/src/index.ts#L655

Thanks
